name: Build base container image
on:
  workflow_dispatch:
    inputs:
      clab_version:
        required: true
        type: string
      ano_priv_key_name:
        required: true
        type: string
      ano_netbox_url:
        required: true
        type: string
      ano_netbox_token:
        required: true
        type: string

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Download source code from repo
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Login to GHCR
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        env:
          ANO_CLAB_VERSION: ${{ inputs.clab_version }}
          ANO_PRIV_KEY_NAME: ${{ inputs.ano_priv_key_name }}
          ANO_NETBOX_URL: ${{ inputs.ano_netbox_url }}
          ANO_NETBOX_TOKEN: ${{ inputs.ano_netbox_token }}
          
        with:
          imageName: ghcr.io/${{ toLower(github.repository) }}/autonetops_base_image
          imageTag: latest
          push: always